# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
# Import all necessary packages
import numpy as np
from numpy import *
import scipy
from scipy import stats, signal
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

# Set random seed for reproducibility
np.random.seed(42)

#### 1. Import the numpy package under the name `np` (ג˜…ג˜†ג˜†)

In [2]:
a=1
print(a)

1


#### 2. Print the numpy version and the configuration (ג˜…ג˜†ג˜†)

#### 3. Create a null vector of size 10 (ג˜…ג˜†ג˜†)

#### 4. How to find the memory size of any array (ג˜…ג˜†ג˜†)

#### 5. How to get the documentation of the numpy add function from the command line? (ג˜…ג˜†ג˜†)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (ג˜…ג˜†ג˜†)

#### 7. Create a vector with values ranging from 10 to 49 (ג˜…ג˜†ג˜†)

#### 8. Reverse a vector (first element becomes last) (ג˜…ג˜†ג˜†)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (ג˜…ג˜†ג˜†)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (ג˜…ג˜†ג˜†)

#### 11. Create a 3x3 identity matrix (ג˜…ג˜†ג˜†)

#### 12. Create a 3x3x3 array with random values (ג˜…ג˜†ג˜†)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (ג˜…ג˜†ג˜†)

#### 14. Create a random vector of size 30 and find the mean value (ג˜…ג˜†ג˜†)

#### 15. Create a 2d array with 1 on the border and 0 inside (ג˜…ג˜†ג˜†)

#### 16. How to add a border (filled with 0's) around an existing array? (ג˜…ג˜†ג˜†)

#### 17. What is the result of the following expression? (ג˜…ג˜†ג˜†)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (ג˜…ג˜†ג˜†)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (ג˜…ג˜†ג˜†)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (ג˜…ג˜†ג˜†)

#### 21. Create a checkerboard 8x8 matrix using the tile function (ג˜…ג˜†ג˜†)

#### 22. Normalize a 5x5 random matrix (ג˜…ג˜†ג˜†)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (ג˜…ג˜†ג˜†)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (ג˜…ג˜†ג˜†)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (ג˜…ג˜†ג˜†)

#### 26. What is the output of the following script? (ג˜…ג˜†ג˜†)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (ג˜…ג˜†ג˜†)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (ג˜…ג˜†ג˜†)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (ג˜…ג˜†ג˜†)

#### 30. How to find common values between two arrays? (ג˜…ג˜†ג˜†)

#### 31. How to ignore all numpy warnings (not recommended)? (ג˜…ג˜†ג˜†)

#### 32. Is the following expressions true? (ג˜…ג˜†ג˜†)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (ג˜…ג˜†ג˜†)

#### 34. How to get all the dates corresponding to the month of July 2016? (ג˜…ג˜…ג˜†)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (ג˜…ג˜…ג˜†)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (ג˜…ג˜…ג˜†)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (ג˜…ג˜…ג˜†)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (ג˜…ג˜†ג˜†)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (ג˜…ג˜…ג˜†)

#### 40. Create a random vector of size 10 and sort it (ג˜…ג˜…ג˜†)

#### 41. How to sum a small array faster than np.sum? (ג˜…ג˜…ג˜†)

#### 42. Consider two random arrays A and B, check if they are equal (ג˜…ג˜…ג˜†)

#### 43. Make an array immutable (read-only) (ג˜…ג˜…ג˜†)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (ג˜…ג˜…ג˜†)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (ג˜…ג˜…ג˜†)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (ג˜…ג˜…ג˜†)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (ג˜…ג˜…ג˜†)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (ג˜…ג˜…ג˜†)

#### 49. How to print all the values of an array? (ג˜…ג˜…ג˜†)

#### 50. How to find the closest value (to a given scalar) in a vector? (ג˜…ג˜…ג˜†)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (ג˜…ג˜…ג˜†)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (ג˜…ג˜…ג˜†)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (ג˜…ג˜…ג˜†)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (ג˜…ג˜…ג˜†)

#### 56. Generate a generic 2D Gaussian-like array (ג˜…ג˜…ג˜†)

#### 57. How to randomly place p elements in a 2D array? (ג˜…ג˜…ג˜†)

In [3]:
# Randomly place p elements in a 2D array
p = 10
shape = (7, 7)
Z = np.zeros(shape)
np.random.seed(0)
Z.flat[np.random.choice(Z.size, p, replace=False)] = 1
print(Z)

[[0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 0. 1. 0. 1.]
 [0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (ג˜…ג˜…ג˜†)

In [4]:
# Subtract the mean of each row of a matrix
Z = np.random.rand(5, 10)
Z -= Z.mean(axis=1, keepdims=True)
print(Z)

[[-0.18780772  0.17988509 -0.10738299  0.44320285 -0.07716498 -0.15849716
   0.03042568 -0.14404046 -0.07139394  0.09277365]
 [ 0.31560469 -0.1370438   0.02606967  0.3153548  -0.48771344  0.38281528
   0.06614625 -0.4160842  -0.22884162  0.16369236]
 [ 0.02344124 -0.2593422  -0.54596401  0.04988463  0.37455984  0.06840088
   0.05066944  0.41091014 -0.0025391  -0.17002084]
 [-0.07080554  0.07800706 -0.20749543  0.12924928 -0.2283013   0.23284244
   0.40406801  0.11702383 -0.53193141  0.07734305]
 [ 0.13955701  0.43784239  0.34409085 -0.02447824 -0.47838792 -0.0829434
  -0.51411495 -0.0923917   0.44548411 -0.17465815]]


#### 59. How to sort an array by the nth column? (ג˜…ג˜…ג˜†)

In [5]:
# Sort an array by the nth column
Z = np.random.randint(0, 10, (10, 3))
n = 2
Z = Z[Z[:, n].argsort()]
print(Z)

[[0 6 0]
 [2 3 0]
 [2 9 1]
 [3 4 1]
 [2 9 2]
 [3 3 2]
 [2 3 2]
 [6 3 3]
 [4 6 8]
 [8 8 8]]


#### 60. How to tell if a given 2D array has null columns? (ג˜…ג˜…ג˜†)

In [6]:
# Tell if a given 2D array has null columns
Z = np.random.randint(0, 3, (10, 10))
Z[:, 0] = 0  # Make first column all zeros
print(np.any(Z, axis=0) == 0)  # Returns boolean array for null columns
print(np.all(Z == 0, axis=0))  # Alternative way

[ True False False False False False False False False False]
[ True False False False False False False False False False]


#### 61. Find the nearest value from a given value in an array (ג˜…ג˜…ג˜†)

In [7]:
# Find the nearest value from a given value in an array
Z = np.random.uniform(0, 100, 10)
v = 10
nearest = Z[np.argmin(np.abs(Z - v))]
print(f"Nearest value to {v}: {nearest}")

Nearest value to 10: 5.03700567575438


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (ג˜…ג˜…ג˜†)

In [8]:
# Compute sum of two arrays (1,3) and (3,1) using an iterator
A = np.arange(3).reshape(1, 3)
B = np.arange(3).reshape(3, 1)
it = np.nditer([A, B, None], flags=['external_loop'], op_flags=[['readonly'], ['readonly'], ['writeonly', 'allocate']])
for x, y, z in it:
    z[...] = x + y
result = it.operands[2]
print(result)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (ג˜…ג˜…ג˜†)

In [9]:
# Create an array class with a name attribute
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name="no name"):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), name="range_array")
print(Z.name)
print(Z)

range_array
[0 1 2 3 4 5 6 7 8 9]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (ג˜…ג˜…ג˜…)

In [10]:
# Add 1 to each element indexed by a second vector
Z = np.ones(10)
I = np.array([3, 3, 9, 3, 4, 1])
Z += np.bincount(I, minlength=Z.size)
print(Z)

[1. 2. 1. 4. 2. 1. 1. 1. 1. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (ג˜…ג˜…ג˜…)

In [11]:
# Accumulate elements of X to array F based on index list I
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 0, 1, 2, 2])
F = np.zeros(3)
np.add.at(F, I, X)
print(F)

[3. 3. 9.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (ג˜…ג˜…ג˜†)

In [12]:
# Compute the number of unique colors in a (w,h,3) image
w, h = 16, 16
I = np.random.randint(0, 256, (w, h, 3), dtype=np.uint8)
# Reshape to (w*h, 3) and get unique rows
colors = np.unique(I.reshape(-1, I.shape[2]), axis=0)
print(f"Number of unique colors: {len(colors)}")

Number of unique colors: 256


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (ג˜…ג˜…ג˜…)

In [13]:
# Get sum over the last two axes of a 4D array
Z = np.random.rand(5, 5, 5, 5)
result = Z.sum(axis=(-2, -1))
print(f'Original shape: {Z.shape}')
print(f'Result shape: {result.shape}')

Original shape: (5, 5, 5, 5)
Result shape: (5, 5)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (ג˜…ג˜…ג˜…)

In [14]:
# Compute means of subsets of D using vector S
D = np.arange(100)
S = np.array([1, 1, 1, 1, 2, 2, 2, 3, 3, 3])
labels = np.repeat(np.arange(len(S)), 10)
means = np.array([D[labels == i].mean() for i in np.unique(labels)])
print(means)

[ 4.5 14.5 24.5 34.5 44.5 54.5 64.5 74.5 84.5 94.5]


#### 69. How to get the diagonal of a dot product? (ג˜…ג˜…ג˜…)

In [15]:
# Get the diagonal of a dot product
A = np.random.uniform(0, 1, (5, 5))
B = np.random.uniform(0, 1, (5, 5))
# Diagonal elements of A @ B without computing full product
diag = np.sum(A * B.T, axis=1)
print(diag)

[1.87125013 1.22865828 1.401404   1.54209759 1.81848103]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (ג˜…ג˜…ג˜…)

In [16]:
# Build a vector with 3 consecutive zeros interleaved in [1,2,3,4,5]
Z = np.array([1, 2, 3, 4, 5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z) - 1) * (nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (ג˜…ג˜…ג˜…)

In [17]:
# Multiply an array of shape (5,5,3) by an array with shape (5,5)
A = np.random.rand(5, 5, 3)
B = np.random.rand(5, 5)
result = A * B[:, :, np.newaxis]
print(result.shape)

(5, 5, 3)


#### 72. How to swap two rows of an array? (ג˜…ג˜…ג˜…)

In [18]:
# Swap two rows of an array
Z = np.arange(20).reshape(4, 5)
Z[[0, 2]] = Z[[2, 0]]
print(Z)

[[10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [15 16 17 18 19]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (ג˜…ג˜…ג˜…)

In [19]:
# Find unique line segments from 10 triplets describing triangles
triangles = np.random.randint(0, 10, (10, 3))
# Get all edges from triangles, sort them, and find unique
edges = np.concatenate([triangles[:, [0, 1]], triangles[:, [1, 2]], triangles[:, [0, 2]]])
edges = np.sort(edges, axis=1)
unique_edges = np.unique(edges, axis=0)
print(unique_edges)

[[0 1]
 [0 2]
 [0 3]
 [0 4]
 [0 5]
 [0 6]
 [0 7]
 [0 8]
 [1 1]
 [1 3]
 [1 6]
 [1 7]
 [1 8]
 [2 2]
 [2 3]
 [2 4]
 [2 7]
 [2 8]
 [3 4]
 [4 6]
 [4 9]
 [5 8]
 [6 8]
 [6 9]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (ג˜…ג˜…ג˜…)

In [20]:
# Produce array A from sorted array C (bincount result)
C = np.array([0, 1, 1, 2, 2, 2, 3])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 2 3 3 4 4 5 5 6 6 6]


#### 75. How to compute averages using a sliding window over an array? (ג˜…ג˜…ג˜…)

In [21]:
# Compute averages using a sliding window over an array
Z = np.arange(10)
window_size = 3
avg = np.convolve(Z, np.ones(window_size) / window_size, mode='valid')
print(avg)

[1. 2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (ג˜…ג˜…ג˜…)

In [22]:
# Build a 2D array with shifted rows from a 1D array
Z = np.arange(5)
n = 5
result = np.lib.stride_tricks.as_strided(np.concatenate([Z] * n), shape=(n, n), strides=(Z.strides[0], Z.strides[0]))
print(result)

[[0 1 2 3 4]
 [1 2 3 4 0]
 [2 3 4 0 1]
 [3 4 0 1 2]
 [4 0 1 2 3]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (ג˜…ג˜…ג˜…)

In [23]:
# Negate a boolean or change the sign of a float inplace
# Negate boolean
Z = np.array([True, False, True])
np.logical_not(Z, out=Z)
print(Z)

# Change sign of float inplace
Z = np.array([-1.5, 2.5, -3.5])
np.negative(Z, out=Z)
print(Z)

[False  True False]
[ 1.5 -2.5  3.5]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (ג˜…ג˜…ג˜…)

In [24]:
# Compute distance from point p to each line
P = np.array([0, 0])
A = np.array([[1, 1], [2, 2], [3, 3]])
B = np.array([[2, 2], [3, 3], [4, 4]])
# Distance from point to line defined by A and B
t = np.sum((P - A) * (B - A), axis=1) / np.sum((B - A) ** 2, axis=1)
d = np.sqrt(np.sum((A + t[:, np.newaxis] * (B - A) - P) ** 2, axis=1))
print(d)

[0. 0. 0.]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (ג˜…ג˜…ג˜…)

In [25]:
# Compute distance from each point in P to each line
P = np.array([[0, 0], [1, 1], [2, 2]])
A = np.array([[1, 1], [2, 2]])
B = np.array([[2, 2], [3, 3]])
# Distances (P, lines) shape (3, 2)
distances = np.zeros((len(P), len(A)))
for i in range(len(P)):
    for j in range(len(A)):
        t = np.dot(P[i] - A[j], B[j] - A[j]) / np.dot(B[j] - A[j], B[j] - A[j])
        distances[i, j] = np.linalg.norm(A[j] + t * (B[j] - A[j]) - P[i])
print(distances)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (ג˜…ג˜…ג˜…)

In [26]:
# Extract a subpart with fixed shape centered on a given element
Z = np.random.randint(0, 10, (10, 10))
shape = (5, 5)
pos = (5, 5)
R = Z[max(0, pos[0]-shape[0]//2):min(Z.shape[0], pos[0]+shape[0]//2+1),
      max(0, pos[1]-shape[1]//2):min(Z.shape[1], pos[1]+shape[1]//2+1)]
print(R.shape)
print(R)

AxisError: axis 3 is out of bounds for array of dimension 0

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (ג˜…ג˜…ג˜…)

In [27]:
# Generate an array with consecutive overlapping subarrays
Z = np.arange(10)
n = 3
result = np.lib.stride_tricks.as_strided(Z, shape=(len(Z)-n+1, n), strides=(Z.strides[0], Z.strides[0]))
print(result)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 82. Compute a matrix rank (ג˜…ג˜…ג˜…)

In [28]:
# Compute a matrix rank
Z = np.random.rand(5, 5)
rank = np.linalg.matrix_rank(Z)
print(f"Matrix rank: {rank}")

Matrix rank: 5


#### 83. How to find the most frequent value in an array?

In [29]:
# Find the most frequent value in an array
Z = np.array([1, 2, 1, 3, 2, 1, 1, 2, 3])
values, counts = np.unique(Z, return_counts=True)
most_frequent = values[np.argmax(counts)]
print(f"Most frequent value: {most_frequent}")

Most frequent value: 1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (ג˜…ג˜…ג˜…)

In [30]:
# Extract all contiguous 3x3 blocks from a 10x10 matrix
Z = np.random.randint(0, 5, (10, 10))
n = 3
blocks = np.lib.stride_tricks.as_strided(Z, shape=(8, 8, n, n), strides=Z.strides + Z.strides)
print(f"Number of blocks: {blocks.shape[0]} x {blocks.shape[1]}")
print(f"Shape of blocks: {blocks.shape}")

Number of blocks: 8 x 8
Shape of blocks: (8, 8, 3, 3)


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (ג˜…ג˜…ג˜…)

In [31]:
# Create a 2D array subclass where Z[i,j] == Z[j,i]
class Symmetric(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return obj
    def __setitem__(self, key, value):
        super().__setitem__(key, value)
        if isinstance(key, tuple) and len(key) == 2:
            i, j = key
            if isinstance(i, int) and isinstance(j, int):
                super().__setitem__((j, i), value)

Z = Symmetric(np.zeros((5, 5)))
Z[0, 1] = 1
print(Z)

[[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (ג˜…ג˜…ג˜…)

In [32]:
# Compute the sum of p matrix products at once
n, p = 5, 3
M = np.random.rand(n, n, p)
# Compute sum of M[:, :, i] @ M[:, :, i] for all i
result = np.einsum('ijk,ljk->il', M, M).sum(axis=-1)
# Alternative: simpler approach
result = np.sum([M[:, :, i] @ M[:, :, i] for i in range(p)], axis=0)
print(result.shape)

(5, 5)


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (ג˜…ג˜…ג˜…)

In [33]:
# Get block-sum for 16x16 array with 4x4 block size
Z = np.random.randint(0, 10, (16, 16))
block_size = 4
result = Z.reshape(4, 4, 4, 4).sum(axis=(1, 3))
print(result.shape)

(4, 4)


#### 88. How to implement the Game of Life using numpy arrays? (ג˜…ג˜…ג˜…)

In [34]:
# Implement Game of Life
def game_of_life_step(Z):
    # Count neighbors
    neighbors = np.zeros_like(Z)
    for i in [-1, 0, 1]:
        for j in [-1, 0, 1]:
            if i == 0 and j == 0:
                continue
            neighbors += np.roll(np.roll(Z, i, axis=0), j, axis=1)
    # Apply rules
    birth = (Z == 0) & (neighbors == 3)
    survive = (Z == 1) & ((neighbors == 2) | (neighbors == 3))
    return np.asarray(birth | survive, dtype=int)

Z = np.random.choice([0, 1], (10, 10))
for _ in range(10):
    Z = game_of_life_step(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 89. How to get the n largest values of an array (ג˜…ג˜…ג˜…)

In [35]:
# Get the n largest values of an array
Z = np.random.randint(0, 100, 20)
n = 5
largest = np.argsort(Z)[-n:][::-1]
print(f"Indices of {n} largest: {largest}")
print(f"Values: {Z[largest]}")

Indices of 5 largest: [18 19  6 14  7]
Values: [85 72 67 67 61]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (ג˜…ג˜…ג˜…)

In [36]:
# Build the cartesian product of arbitrary number of vectors
def cartesian(*arrays):
    la = len(arrays)
    L = *map(np.asarray, arrays), 
    arr = np.empty([len(a) for a in L] + [la], dtype=np.int64)
    for i, a in enumerate(np.ix_(*L)):
        arr[..., i] = a
    return arr.reshape(-1, la)

X = np.array([1, 2, 3])
Y = np.array([4, 5])
result = cartesian(X, Y)
print(result)

[[1 4]
 [1 5]
 [2 4]
 [2 5]
 [3 4]
 [3 5]]


#### 91. How to create a record array from a regular array? (ג˜…ג˜…ג˜…)

In [37]:
# Create a record array from a regular array
Z = np.array([(1, 'first'), (2, 'second'), (3, 'third')], dtype=[('id', 'i4'), ('name', 'U10')])
print(Z)
print(Z['id'])
print(Z['name'])

[(1, 'first') (2, 'second') (3, 'third')]
[1 2 3]
['first' 'second' 'third']


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (ג˜…ג˜…ג˜…)

In [38]:
# Compute Z^3 using 3 different methods
Z = np.array([1, 2, 3, 4])

# Method 1: multiplication
result1 = Z * Z * Z

# Method 2: power function
result2 = np.power(Z, 3)

# Method 3: using einsum
result3 = np.einsum('i,i,i->', Z, Z, Z) if Z.size == 1 else Z * Z * Z

print(result1)
print(result2)
print(result3)

[ 1  8 27 64]
[ 1  8 27 64]
[ 1  8 27 64]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (ג˜…ג˜…ג˜…)

In [39]:
# Find rows of A that contain elements of each row of B
A = np.array([[1, 2, 3], [2, 3, 4], [5, 6, 7], [1, 3, 5]])
B = np.array([[2, 3], [5, 6]])
# For each row in B, find rows in A containing all elements
for b in B:
    mask = np.all(np.isin(A, b), axis=1)
    print(f"Rows of A containing {b}: {np.where(mask)[0]}")

Rows of A containing [2 3]: []
Rows of A containing [5 6]: []


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (ג˜…ג˜…ג˜…)

In [40]:
# Extract rows with unequal values from 10x3 matrix
Z = np.random.randint(0, 5, (10, 3))
# Keep only rows where not all elements are equal
mask = ~np.all(Z == Z[:, :1], axis=1)
result = Z[mask]
print(result)

[[2 1 4]
 [4 3 1]
 [0 4 2]
 [3 0 0]
 [0 3 2]
 [4 3 3]
 [2 0 4]
 [1 0 0]
 [2 1 4]
 [4 4 2]]


#### 95. Convert a vector of ints into a matrix binary representation (ג˜…ג˜…ג˜…)

In [41]:
# Convert vector of ints to binary matrix
Z = np.array([0, 1, 2, 3, 4, 5, 6, 7])
B = ((Z[:, np.newaxis] & (1 << np.arange(8))) > 0).astype(int)
print(B)

[[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 1 0 0 0 0 0]
 [0 1 1 0 0 0 0 0]
 [1 1 1 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (ג˜…ג˜…ג˜…)

In [42]:
# Extract unique rows from 2D array
Z = np.array([[1, 2], [3, 4], [1, 2], [5, 6], [3, 4]])
unique_rows = np.unique(Z, axis=0)
print(unique_rows)

[[1 2]
 [3 4]
 [5 6]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (ג˜…ג˜…ג˜…)

In [43]:
# Einsum equivalents of inner, outer, sum, and mul
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Inner product
inner = np.einsum('i,i->', A, B)
print(f"Inner: {inner}")

# Outer product
outer = np.einsum('i,j->ij', A, B)
print(f"Outer:\n{outer}")

# Sum
sum_result = np.einsum('i->', A)
print(f"Sum: {sum_result}")

# Element-wise multiply
mul = np.einsum('i,i->i', A, B)
print(f"Multiply: {mul}")

Inner: 32
Outer:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum: 6
Multiply: [ 4 10 18]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (ג˜…ג˜…ג˜…)?

In [44]:
# Sample a path using equidistant samples
def sample_equidistant(curve, n_samples):
    # Compute cumulative distance along curve
    distances = np.cumsum(np.linalg.norm(np.diff(curve, axis=0), axis=1))
    distances = np.insert(distances, 0, 0)
    # Interpolate at equidistant points
    equidist_points = np.linspace(0, distances[-1], n_samples)
    sampled = np.array([np.interp(equidist_points, distances, curve[:, i]) for i in range(curve.shape[1])]).T
    return sampled

curve = np.array([[0, 0], [1, 1], [2, 0], [3, 1], [4, 0]])
sampled = sample_equidistant(curve, 20)
print(sampled)

[[0.         0.        ]
 [0.21052632 0.21052632]
 [0.42105263 0.42105263]
 [0.63157895 0.63157895]
 [0.84210526 0.84210526]
 [1.05263158 0.94736842]
 [1.26315789 0.73684211]
 [1.47368421 0.52631579]
 [1.68421053 0.31578947]
 [1.89473684 0.10526316]
 [2.10526316 0.10526316]
 [2.31578947 0.31578947]
 [2.52631579 0.52631579]
 [2.73684211 0.73684211]
 [2.94736842 0.94736842]
 [3.15789474 0.84210526]
 [3.36842105 0.63157895]
 [3.57894737 0.42105263]
 [3.78947368 0.21052632]
 [4.         0.        ]]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (ג˜…ג˜…ג˜…)

In [45]:
# Select rows from multinomial distribution
def is_multinomial(row, n_samples=10):
    # Check if row could be result of multinomial draw
    return np.sum(row) == n_samples and np.all(row >= 0) and np.all(row == np.round(row))

Z = np.array([[10, 0, 0], [8, 1, 1], [5, 3, 2]])
mask = np.array([is_multinomial(row) for row in Z])
result = Z[mask]
print(result)

[[10  0  0]
 [ 8  1  1]
 [ 5  3  2]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (ג˜…ג˜…ג˜…)

In [46]:
# Compute bootstrapped 95% confidence intervals for mean
Z = np.random.normal(100, 15, 100)
N = 1000
bootstrap_means = np.array([np.random.choice(Z, len(Z)).mean() for _ in range(N)])
ci_lower, ci_upper = np.percentile(bootstrap_means, [2.5, 97.5])
print(f"95% CI: [{ci_lower:.2f}, {ci_upper:.2f}]")
print(f"Sample mean: {Z.mean():.2f}")

95% CI: [96.71, 101.76]


Sample mean: 99.20
